### ISSUE TITLE
Add react-native 0.70.x support 

### ISSUE THREAD

**Issue by retyui** [jpudysz/react-native-is-maestro#11]
Can't install & use this module on older RN version 0.70.x

**Comment by jpudysz** [comment]
Hello, @retyui. I don't have plans to support the older versions of React Native. I have a few reasons why:
- From the native code perspective, RN 0.70 and RN 0.71 differs a lot. Supporting the older version is not that trivial
- React Native 0.71 was released at the beginning of January. Soon next version will be released, so the community needs to keep up with the pace. Otherwise, we won't move with Fabric and other goodies related to NativeModules
- I do it in my spare time; I don't have older projects with the maestro, so for me, it will be time-consuming to even prepare the environment

I hope you understand my point. I'm happy to support upcoming versions of React Native

**Comment by retyui** [comment]
how about `80%` who haven't migrated to the latest version, Is it still no matter?

![image](https://user-images.githubusercontent.com/4661784/219631910-e39bafec-787b-4369-9d3a-dc7f574e9c77.png)

RN version break:  https://rn-versions.github.io/

**Comment by jpudysz** [comment]
I don't know what about them. What about updating your codebase to React Native 0.71? What's blocking you?
I am happy to accept your PR with support for older RN versions. I won't dedicate my limited time to supporting older versions of RN.

**Comment by retyui** [comment]
**UPD:** I create a own module that support old versions of react native 

https://github.com/retyui/react-native-detect-maestro
